name: publish-nugets-and-symbols
description: Publish Nugets & Symbols

inputs:
  version: 
    description: 'Version'
    default: '0.0.1'
    required: false
  api_key:
    description: 'API Key'
    default: ''
    required: true

runs:
  using: 'composite'
  steps:

  - name: Publish DotNet
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: 9.0.x

  - name: Publish the package to nuget.org
    shell: bash
    run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
    env:
      NUGET_AUTH_TOKEN: ${{ inputs.api_key }}