name: publish-nugets-and-symbols
description: Publish Nugets & Symbols

inputs:
  version: 
    description: 'Version'
    default: '0.0.1'
    required: false

runs:
  using: 'composite'
  steps:

  - name: Publish DotNet
    uses: SpringHgui/publish-nuget@1.0.1
    with:
      PROJECT_FILE_PATH: src/Hermsoft.EntityFrameworkCore.DynamicOData/Hermsoft.EntityFrameworkCore.DynamicOData.csproj
      VERSION_STATIC: ${{ inputs.version }}
      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      INCLUDE_SYMBOLS: true