// <auto-generated />
using System;
using Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20240329083447_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "sales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc420210-e68b-466a-b942-7ac851c4a970"),
                            Name = "Direct Program Associate"
                        },
                        new
                        {
                            Id = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49"),
                            Name = "Customer Directives Coordinator"
                        },
                        new
                        {
                            Id = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9"),
                            Name = "Future Optimization Director"
                        },
                        new
                        {
                            Id = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3"),
                            Name = "Customer Identity Consultant"
                        },
                        new
                        {
                            Id = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9"),
                            Name = "Customer Program Designer"
                        },
                        new
                        {
                            Id = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8"),
                            Name = "Investor Markets Engineer"
                        },
                        new
                        {
                            Id = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1"),
                            Name = "Senior Accountability Developer"
                        },
                        new
                        {
                            Id = new Guid("f7cee502-570b-409d-9e58-c086228dadc9"),
                            Name = "Principal Response Planner"
                        },
                        new
                        {
                            Id = new Guid("926253dd-2d35-40b4-b672-50b419586515"),
                            Name = "International Operations Engineer"
                        },
                        new
                        {
                            Id = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2"),
                            Name = "Chief Research Director"
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "sales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            Email = "Francesca56@hotmail.com",
                            Name = "Francesca"
                        },
                        new
                        {
                            Id = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            Email = "Brianne_Jacobs97@hotmail.com",
                            Name = "Brianne"
                        },
                        new
                        {
                            Id = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            Email = "Earl.Braun@yahoo.com",
                            Name = "Earl"
                        },
                        new
                        {
                            Id = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            Email = "Kadin.Macejkovic@gmail.com",
                            Name = "Kadin"
                        },
                        new
                        {
                            Id = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            Email = "Armando_Schuppe55@gmail.com",
                            Name = "Armando"
                        },
                        new
                        {
                            Id = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            Email = "Marques.Tillman@gmail.com",
                            Name = "Marques"
                        },
                        new
                        {
                            Id = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            Email = "Bryana.Ondricka22@yahoo.com",
                            Name = "Bryana"
                        },
                        new
                        {
                            Id = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            Email = "Abigail_Kreiger71@hotmail.com",
                            Name = "Abigail"
                        },
                        new
                        {
                            Id = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            Email = "Odell.Armstrong57@gmail.com",
                            Name = "Odell"
                        },
                        new
                        {
                            Id = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            Email = "Lura.Beahan86@yahoo.com",
                            Name = "Lura"
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "sales");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("fc420210-e68b-466a-b942-7ac851c4a970")
                        },
                        new
                        {
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("c0b29ec8-8c69-48be-ab79-2292ed3a5b98"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f"),
                            RoleId = new Guid("cbd5b029-7a33-4d44-85c1-3a100ec03be9")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("62581e93-0bf6-402e-a225-f4b60cdfe3c2")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("f7cee502-570b-409d-9e58-c086228dadc9")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("5e3e9cf6-dc17-4c9e-852f-f7cc39de00c8")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("926253dd-2d35-40b4-b672-50b419586515")
                        },
                        new
                        {
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("b9307b02-11cc-40e8-a4af-80929c86c4c3")
                        },
                        new
                        {
                            UserId = new Guid("1bd7a0ac-a730-4396-96ce-c567756a1d1b"),
                            RoleId = new Guid("47928d1f-d692-4f4e-8be0-2d3e8fbf6de9")
                        },
                        new
                        {
                            UserId = new Guid("ec3b9b71-5663-4110-82d6-c5d9b43c0c29"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("f9a0826e-3011-48a1-966e-9b2882295ff1")
                        },
                        new
                        {
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791"),
                            RoleId = new Guid("cba2a3d4-cd42-4d7a-98c8-a7832ce0ec49")
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("OderedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OderedOn = new DateTimeOffset(new DateTime(2024, 2, 22, 5, 32, 49, 19, DateTimeKind.Unspecified).AddTicks(8598), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 5602.402592016024760m,
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791")
                        },
                        new
                        {
                            Id = 2,
                            OderedOn = new DateTimeOffset(new DateTime(2019, 5, 2, 18, 7, 17, 760, DateTimeKind.Unspecified).AddTicks(404), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 677.1253199460393430m,
                            UserId = new Guid("e19298ee-809d-48d1-bea4-6cb1a7285f02")
                        },
                        new
                        {
                            Id = 3,
                            OderedOn = new DateTimeOffset(new DateTime(2021, 1, 1, 8, 26, 5, 412, DateTimeKind.Unspecified).AddTicks(1991), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 2553.973788429856960m,
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232")
                        },
                        new
                        {
                            Id = 4,
                            OderedOn = new DateTimeOffset(new DateTime(2023, 4, 24, 1, 57, 3, 243, DateTimeKind.Unspecified).AddTicks(537), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 436.323012569336140m,
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7")
                        },
                        new
                        {
                            Id = 5,
                            OderedOn = new DateTimeOffset(new DateTime(2020, 9, 8, 20, 31, 2, 231, DateTimeKind.Unspecified).AddTicks(3478), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 2858.722970300680270m,
                            UserId = new Guid("e8840eba-659e-4c76-8450-35c9f5e2225f")
                        },
                        new
                        {
                            Id = 6,
                            OderedOn = new DateTimeOffset(new DateTime(2023, 7, 6, 2, 18, 7, 195, DateTimeKind.Unspecified).AddTicks(2919), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 2935.213836108473320m,
                            UserId = new Guid("58ffa499-e39c-49c1-9fd5-67674de9e2e7")
                        },
                        new
                        {
                            Id = 7,
                            OderedOn = new DateTimeOffset(new DateTime(2020, 2, 18, 19, 3, 55, 191, DateTimeKind.Unspecified).AddTicks(511), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 3612.509413034500120m,
                            UserId = new Guid("a2680da1-59cd-4c5e-b758-e5564eae2fb3")
                        },
                        new
                        {
                            Id = 8,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 5, 30, 21, 30, 24, 144, DateTimeKind.Unspecified).AddTicks(9181), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 1229.993892369971830m,
                            UserId = new Guid("3ea4f195-81c5-400a-8eed-d994ed094232")
                        },
                        new
                        {
                            Id = 9,
                            OderedOn = new DateTimeOffset(new DateTime(2021, 7, 7, 15, 15, 0, 290, DateTimeKind.Unspecified).AddTicks(6742), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 2321.484828339355090m,
                            UserId = new Guid("a66b0d01-aa75-41ed-9fbf-a01e487c537c")
                        },
                        new
                        {
                            Id = 10,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 10, 22, 2, 30, 52, 250, DateTimeKind.Unspecified).AddTicks(5578), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 3415.163941275399190m,
                            UserId = new Guid("276fa469-60ff-4858-bc97-0d5ad9955791")
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts", "sales");

                    b.HasData(
                        new
                        {
                            OrderId = 8,
                            ProductId = new Guid("3fc279a5-b88d-44bd-85d3-03c276bd1b11"),
                            Number = 5
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = new Guid("ea30040a-4d3f-4f71-a81a-e6ea473afa54"),
                            Number = 4
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = new Guid("25b0d695-0f39-4095-aaaa-f93b4720c5c4"),
                            Number = 10
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = new Guid("9a511daf-86ee-4e93-88c2-0baa77a6d388"),
                            Number = 3
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = new Guid("308fe456-1d7e-414c-b80d-1dc9c9e354b9"),
                            Number = 5
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = new Guid("8a373229-f68d-443e-b2e6-3476ba8b9c83"),
                            Number = 7
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = new Guid("25b0d695-0f39-4095-aaaa-f93b4720c5c4"),
                            Number = 2
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = new Guid("3fc279a5-b88d-44bd-85d3-03c276bd1b11"),
                            Number = 5
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = new Guid("9a511daf-86ee-4e93-88c2-0baa77a6d388"),
                            Number = 8
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("d06868bb-b0a2-462f-b87c-ecb48a731684"),
                            Number = 9
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("9a511daf-86ee-4e93-88c2-0baa77a6d388"),
                            Number = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("3fc279a5-b88d-44bd-85d3-03c276bd1b11"),
                            Number = 3
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = new Guid("ea30040a-4d3f-4f71-a81a-e6ea473afa54"),
                            Number = 3
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("1f63a613-2ca0-4858-b94b-e6419dd1197b"),
                            Number = 7
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = new Guid("3fc279a5-b88d-44bd-85d3-03c276bd1b11"),
                            Number = 1
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = new Guid("25b0d695-0f39-4095-aaaa-f93b4720c5c4"),
                            Number = 7
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = new Guid("7981f46b-bbd5-4b0b-b8ce-8d2a43f205ea"),
                            Number = 10
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", "sales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fc279a5-b88d-44bd-85d3-03c276bd1b11"),
                            Category = 0,
                            Description = "Adipisci voluptas nihil magni nobis neque quo.\nEnim facere rerum suscipit suscipit.\nIusto aspernatur non rerum voluptatibus magnam aut sint et consequuntur.\nIpsam voluptatem qui rerum.\nEligendi magni rerum.",
                            Price = 122.290348402171870m
                        },
                        new
                        {
                            Id = new Guid("1fd5ab82-b7fc-45ff-b53e-50409c07585b"),
                            Category = 0,
                            Description = "Et deleniti alias similique consequatur est molestiae aut voluptates et.\nAutem libero magni vero quis qui inventore doloremque qui et.\nSuscipit facilis tenetur et ab similique ab.\nRecusandae velit ut voluptatem excepturi et et officiis quia ut.\nVoluptates pariatur sit.",
                            Price = 465.883130502119880m
                        },
                        new
                        {
                            Id = new Guid("7981f46b-bbd5-4b0b-b8ce-8d2a43f205ea"),
                            Category = 2,
                            Description = "Esse ad porro voluptatum aut molestiae in quibusdam est.\nPorro dolores voluptatem et accusamus iste.\nQuo enim molestias et aliquid aut et commodi voluptatibus.\nVoluptatem quasi inventore dignissimos quam est.\nPariatur quos incidunt repellat similique repellendus et.",
                            Price = 409.545110452462380m
                        },
                        new
                        {
                            Id = new Guid("308fe456-1d7e-414c-b80d-1dc9c9e354b9"),
                            Category = 2,
                            Description = "Doloremque odit sit.\nQuidem vero dolorem nulla voluptatem.\nEx qui dolores dolor ut tempore.\nRerum aspernatur et sed consequatur.\nItaque ducimus voluptate quam qui ad voluptatem.",
                            Price = 340.819338629430490m
                        },
                        new
                        {
                            Id = new Guid("1f63a613-2ca0-4858-b94b-e6419dd1197b"),
                            Category = 1,
                            Description = "Voluptatem autem similique vero vel ea ratione reprehenderit architecto ex.\nVoluptatem nulla impedit nisi.\nEos nobis vel qui sed quo ex.\nVoluptatem sapiente fuga consequatur dolore.\nEos voluptas nesciunt.",
                            Price = 162.974443957554310m
                        },
                        new
                        {
                            Id = new Guid("9a511daf-86ee-4e93-88c2-0baa77a6d388"),
                            Category = 1,
                            Description = "Id sint optio at dolor error quod quasi expedita fuga.\nEligendi deserunt nobis et laborum debitis sed fugiat sint esse.\nEius esse placeat vitae eaque.\nEt est nihil dolor explicabo aliquid voluptates dignissimos et.\nAtque fugit eveniet qui consequatur.",
                            Price = 143.460996027322530m
                        },
                        new
                        {
                            Id = new Guid("d06868bb-b0a2-462f-b87c-ecb48a731684"),
                            Category = 2,
                            Description = "Adipisci perferendis voluptatum corrupti.\nIn itaque sit qui possimus consequatur ut beatae cum qui.\nEt et laudantium beatae autem mollitia vel.\nFuga aperiam fuga.\nAdipisci ut enim.",
                            Price = 157.889987861292110m
                        },
                        new
                        {
                            Id = new Guid("ea30040a-4d3f-4f71-a81a-e6ea473afa54"),
                            Category = 2,
                            Description = "Sed necessitatibus voluptatem alias laborum qui.\nDeserunt amet et incidunt ut et voluptatem.\nQuam enim fugit fugit dolor ab sunt.\nIpsam qui blanditiis molestiae.\nRepellat modi dolore aut et maiores alias tempore libero.",
                            Price = 357.802131642519960m
                        },
                        new
                        {
                            Id = new Guid("8a373229-f68d-443e-b2e6-3476ba8b9c83"),
                            Category = 1,
                            Description = "Et sit enim voluptas nemo.\nVoluptates cumque ut exercitationem minima aspernatur et molestias.\nVoluptas maiores nulla aut consequuntur animi.\nEsse quos harum cumque quia quia voluptate eos asperiores velit.\nUllam sint doloribus consectetur et assumenda sint.",
                            Price = 417.035179398569330m
                        },
                        new
                        {
                            Id = new Guid("25b0d695-0f39-4095-aaaa-f93b4720c5c4"),
                            Category = 1,
                            Description = "Ex voluptatem saepe praesentium ullam molestiae reprehenderit harum quos dolores.\nRerum autem dolor ut occaecati eveniet nemo ut nulla.\nEum quisquam cupiditate harum.\nEveniet dicta aut aut repellendus saepe vero culpa.\nQuia ut voluptate voluptate.",
                            Price = 200.534207402497630m
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.UserRole", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.OrderProduct", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
