// <auto-generated />
using System;
using Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Migrations
{
    [DbContext(typeof(DynamicODataDbContext))]
    [Migration("20240320115659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b"),
                            Name = "Direct Configuration Analyst"
                        },
                        new
                        {
                            Id = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933"),
                            Name = "International Security Associate"
                        },
                        new
                        {
                            Id = new Guid("e2045953-adf6-41c6-b823-64661714aac3"),
                            Name = "Central Identity Officer"
                        },
                        new
                        {
                            Id = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83"),
                            Name = "Forward Paradigm Supervisor"
                        },
                        new
                        {
                            Id = new Guid("84270375-4a7b-4191-9365-27515e326c07"),
                            Name = "Human Configuration Architect"
                        },
                        new
                        {
                            Id = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24"),
                            Name = "Corporate Brand Planner"
                        },
                        new
                        {
                            Id = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11"),
                            Name = "Regional Functionality Architect"
                        },
                        new
                        {
                            Id = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca"),
                            Name = "Investor Factors Director"
                        },
                        new
                        {
                            Id = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255"),
                            Name = "Customer Integration Producer"
                        },
                        new
                        {
                            Id = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1"),
                            Name = "Investor Infrastructure Associate"
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            Email = "Lula_Hagenes83@hotmail.com",
                            Name = "Lula"
                        },
                        new
                        {
                            Id = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            Email = "Terrence8@hotmail.com",
                            Name = "Terrence"
                        },
                        new
                        {
                            Id = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            Email = "Hailey35@yahoo.com",
                            Name = "Hailey"
                        },
                        new
                        {
                            Id = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            Email = "Leola_Bartell24@hotmail.com",
                            Name = "Leola"
                        },
                        new
                        {
                            Id = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            Email = "Mason_Prohaska@gmail.com",
                            Name = "Mason"
                        },
                        new
                        {
                            Id = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            Email = "Aurelie_Murphy8@gmail.com",
                            Name = "Aurelie"
                        },
                        new
                        {
                            Id = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            Email = "Garland32@hotmail.com",
                            Name = "Garland"
                        },
                        new
                        {
                            Id = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            Email = "Alisa.Kertzmann66@yahoo.com",
                            Name = "Alisa"
                        },
                        new
                        {
                            Id = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            Email = "Alvina.Beahan41@gmail.com",
                            Name = "Alvina"
                        },
                        new
                        {
                            Id = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            Email = "Emile_Jacobs16@hotmail.com",
                            Name = "Emile"
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("53f83577-9bd2-4cb1-9dbf-94f0bc9bd08b")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("ab0d1ecb-ca32-4410-b9fb-66227beafb2a"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("3c45b109-7fe7-4d13-833f-a362dad09255")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("12b0ad2d-b2b8-43a5-8d43-ae98fb5b9933")
                        },
                        new
                        {
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252"),
                            RoleId = new Guid("ecc1caaa-3a3c-4fb9-aa43-a2c10f4d4b11")
                        },
                        new
                        {
                            UserId = new Guid("b9fa8877-2987-411e-b01a-a8f8f468aa12"),
                            RoleId = new Guid("aa3499e8-35dd-4807-a336-1d0d147942e1")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("0af908c1-ed6c-49c8-91c2-30bedee5469e"),
                            RoleId = new Guid("e2045953-adf6-41c6-b823-64661714aac3")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("ded8b2d6-bf6c-4bd8-a01a-a67863307d24")
                        },
                        new
                        {
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525"),
                            RoleId = new Guid("84270375-4a7b-4191-9365-27515e326c07")
                        },
                        new
                        {
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        },
                        new
                        {
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da"),
                            RoleId = new Guid("feaa9549-1a3d-4798-abc3-c0d2445b8aca")
                        },
                        new
                        {
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81"),
                            RoleId = new Guid("9847f812-bc9f-4202-b3cf-ab4736ac4b83")
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("OderedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OderedOn = new DateTimeOffset(new DateTime(2019, 6, 27, 9, 50, 45, 837, DateTimeKind.Unspecified).AddTicks(9546), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 3297.142318029015820m,
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252")
                        },
                        new
                        {
                            Id = 2,
                            OderedOn = new DateTimeOffset(new DateTime(2019, 12, 7, 8, 26, 8, 780, DateTimeKind.Unspecified).AddTicks(6962), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 2858.994959849721820m,
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31")
                        },
                        new
                        {
                            Id = 3,
                            OderedOn = new DateTimeOffset(new DateTime(2020, 5, 1, 19, 10, 41, 229, DateTimeKind.Unspecified).AddTicks(423), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 3163.810148245459630m,
                            UserId = new Guid("8f96dda5-97f5-45a8-a3e1-5bc40d31bf31")
                        },
                        new
                        {
                            Id = 4,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 2, 16, 8, 52, 52, 659, DateTimeKind.Unspecified).AddTicks(9683), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 3603.499611863080270m,
                            UserId = new Guid("2704a669-6a44-461f-98d0-e8d3f4459525")
                        },
                        new
                        {
                            Id = 5,
                            OderedOn = new DateTimeOffset(new DateTime(2020, 5, 24, 14, 55, 39, 164, DateTimeKind.Unspecified).AddTicks(4947), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 6735.676321353297880m,
                            UserId = new Guid("fcac228e-f7e7-42e4-b34d-5516d9460252")
                        },
                        new
                        {
                            Id = 6,
                            OderedOn = new DateTimeOffset(new DateTime(2024, 1, 27, 8, 42, 57, 841, DateTimeKind.Unspecified).AddTicks(1070), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 4233.250988790866560m,
                            UserId = new Guid("d5eb7384-bb02-432e-a984-53717aef48aa")
                        },
                        new
                        {
                            Id = 7,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 7, 18, 21, 24, 50, 523, DateTimeKind.Unspecified).AddTicks(1039), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 4606.61770865728030m,
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81")
                        },
                        new
                        {
                            Id = 8,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 3, 11, 12, 49, 42, 827, DateTimeKind.Unspecified).AddTicks(4517), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 3279.493968512423020m,
                            UserId = new Guid("d44979b3-d2b7-4228-85cf-6d3eb6c4c4da")
                        },
                        new
                        {
                            Id = 9,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 7, 18, 22, 52, 54, 974, DateTimeKind.Unspecified).AddTicks(76), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 1333.860271952596060m,
                            UserId = new Guid("85b9dcb2-5dea-43aa-a6a2-85345145be81")
                        },
                        new
                        {
                            Id = 10,
                            OderedOn = new DateTimeOffset(new DateTime(2022, 3, 7, 23, 34, 31, 626, DateTimeKind.Unspecified).AddTicks(7022), new TimeSpan(0, 1, 0, 0, 0)),
                            TotalPrice = 6213.46954525338790m,
                            UserId = new Guid("00801dd5-ca2d-40a3-8a8e-75a7adfaca1b")
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            OrderId = 7,
                            ProductId = new Guid("b9547288-646c-40f4-a12d-c6392be029a9"),
                            Number = 2
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = new Guid("aab6b14e-dbbf-42e1-a1ab-e3f079169d8a"),
                            Number = 7
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = new Guid("61e48d59-280f-4353-8e92-056364a8b0c8"),
                            Number = 9
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = new Guid("b9547288-646c-40f4-a12d-c6392be029a9"),
                            Number = 7
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("5afb1f49-b2f0-4763-a873-53fbee4d5ea0"),
                            Number = 1
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = new Guid("61e48d59-280f-4353-8e92-056364a8b0c8"),
                            Number = 4
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = new Guid("5afb1f49-b2f0-4763-a873-53fbee4d5ea0"),
                            Number = 2
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = new Guid("f288ffef-8cc5-47db-9f47-670f31e089c3"),
                            Number = 1
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = new Guid("61e48d59-280f-4353-8e92-056364a8b0c8"),
                            Number = 7
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = new Guid("61e48d59-280f-4353-8e92-056364a8b0c8"),
                            Number = 10
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = new Guid("7068c1aa-f8ba-4cda-b948-92b3ae9d2d84"),
                            Number = 9
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("dbff6dac-e1a0-400d-95b6-97726cb8c220"),
                            Number = 8
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = new Guid("dbff6dac-e1a0-400d-95b6-97726cb8c220"),
                            Number = 10
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = new Guid("3506cfdf-45ff-4309-8d6e-96953b411db5"),
                            Number = 5
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = new Guid("3506cfdf-45ff-4309-8d6e-96953b411db5"),
                            Number = 5
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = new Guid("c2cc2294-7473-4d13-be4d-2bfecb452cee"),
                            Number = 9
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = new Guid("3506cfdf-45ff-4309-8d6e-96953b411db5"),
                            Number = 4
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = new Guid("aab6b14e-dbbf-42e1-a1ab-e3f079169d8a"),
                            Number = 10
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5afb1f49-b2f0-4763-a873-53fbee4d5ea0"),
                            Category = 0,
                            Description = "Quae alias tempore.\nId rerum et rem ratione dicta necessitatibus.\nPraesentium voluptates totam laboriosam eaque reiciendis neque tempora ipsam quia.\nMaxime ut nihil veniam.\nMaxime temporibus ut dolore nesciunt quo eius molestiae.",
                            Price = 404.397414031759810m
                        },
                        new
                        {
                            Id = new Guid("dbff6dac-e1a0-400d-95b6-97726cb8c220"),
                            Category = 2,
                            Description = "Vel qui qui mollitia aut.\nIn sit quam odio aspernatur distinctio labore nesciunt.\nVelit et non sit nulla doloribus suscipit.\nNihil itaque illum facilis.\nRepellendus ut blanditiis vel laudantium esse culpa eum deserunt perspiciatis.",
                            Price = 291.989514051445760m
                        },
                        new
                        {
                            Id = new Guid("b9547288-646c-40f4-a12d-c6392be029a9"),
                            Category = 0,
                            Description = "Praesentium velit voluptatem reprehenderit.\nEnim consequuntur aut harum ullam dolorem blanditiis sed vero.\nOccaecati cumque nulla vel.\nEt ut id mollitia harum pariatur blanditiis rerum excepturi sed.\nIllum cum accusamus vero dolorem itaque suscipit quae.",
                            Price = 159.784193200983180m
                        },
                        new
                        {
                            Id = new Guid("aab6b14e-dbbf-42e1-a1ab-e3f079169d8a"),
                            Category = 2,
                            Description = "A expedita reiciendis illo minima doloribus beatae nesciunt quidem.\nEt repellendus maxime laborum omnis voluptatem ea labore earum vitae.\nQuia dolores voluptate sed.\nNihil repudiandae ut odio sapiente fugiat beatae.\nIste id laborum.",
                            Price = 185.909284769374380m
                        },
                        new
                        {
                            Id = new Guid("c2cc2294-7473-4d13-be4d-2bfecb452cee"),
                            Category = 0,
                            Description = "Et sunt quo harum explicabo sint tenetur.\nEnim fuga repudiandae.\nQuisquam qui voluptatem inventore neque saepe.\nEa est laudantium cupiditate.\nVoluptatem ut ut ab voluptatibus ducimus quo et quia debitis.",
                            Price = 186.665222618532340m
                        },
                        new
                        {
                            Id = new Guid("64ee64aa-2b73-4bb9-8b4f-e71cc1e3ab66"),
                            Category = 1,
                            Description = "Quia dicta id similique dolor impedit qui voluptas voluptatem natus.\nDoloribus ducimus necessitatibus.\nModi aperiam dolorem nostrum.\nQuo dolores natus quidem ea sunt sed dolorum sed ipsum.\nDolorem consequatur eos voluptate eaque quaerat autem non expedita.",
                            Price = 472.975635138031260m
                        },
                        new
                        {
                            Id = new Guid("61e48d59-280f-4353-8e92-056364a8b0c8"),
                            Category = 1,
                            Description = "Cupiditate quidem dignissimos sunt culpa.\nEt autem rerum aut.\nEst totam assumenda animi quam.\nTempore dolores aut et dolores.\nEst enim voluptatem.",
                            Price = 489.069272819944590m
                        },
                        new
                        {
                            Id = new Guid("7068c1aa-f8ba-4cda-b948-92b3ae9d2d84"),
                            Category = 0,
                            Description = "Cumque quibusdam nulla sed ducimus aperiam eaque libero sunt aut.\nCum eum adipisci inventore iusto blanditiis velit.\nSoluta eveniet adipisci impedit sunt suscipit hic voluptas recusandae.\nAutem aut quidem id et.\nIpsum ea sit ut ea dolor numquam.",
                            Price = 442.946250739041970m
                        },
                        new
                        {
                            Id = new Guid("f288ffef-8cc5-47db-9f47-670f31e089c3"),
                            Category = 2,
                            Description = "Quod amet repudiandae adipisci sit molestiae earum modi.\nA eaque dolore quas aspernatur non reprehenderit.\nModi unde ullam quisquam quam.\nQuidem eos corrupti est ratione ullam.\nVoluptate magni minus ullam porro dolor sunt.",
                            Price = 72.434936204608380m
                        },
                        new
                        {
                            Id = new Guid("3506cfdf-45ff-4309-8d6e-96953b411db5"),
                            Category = 0,
                            Description = "Enim reprehenderit ratione quis vel.\nUllam harum delectus cum corporis.\nNumquam quo laborum quis dolorem provident nihil atque.\nAutem quia vel animi atque doloremque amet.\nIncidunt rerum libero ab.",
                            Price = 313.744050048589570m
                        });
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.UserRole", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.OrderProduct", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Identity.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.Sales.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
