// <auto-generated />
using System;
using Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Migrations.HRDb
{
    [DbContext(typeof(HRDbContext))]
    [Migration("20240329083458_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills", "hr");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workers", "hr");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.WorkerSkill", b =>
                {
                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("WorkerId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("WorkerSkills", "hr");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.WorkerSkill", b =>
                {
                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.Skill", "Skill")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.Worker", "Worker")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.Skill", b =>
                {
                    b.Navigation("WorkerSkills");
                });

            modelBuilder.Entity("Hermsoft.EntityFrameworkCore.DynamicOData.TestWebApi.Models.HR.Worker", b =>
                {
                    b.Navigation("WorkerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
