name: build-and-test
description: Build & Test

inputs:
  build-configuration:
    description: 'Build Configuration'
    default: 'Debug'
    required: false
  version: 
    description: 'Version'
    default: '0.0.1'
    required: false

runs:
  using: 'composite'
  steps:
  
  - uses: actions/checkout@v3
  
  - name: Setup .NET
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: 9.0.x

  - name: Restore dependencies
    shell: bash
    run: dotnet restore

  - name: Build
    shell: bash
    run: dotnet build --no-restore -c ${{ inputs.build-configuration }} -p:AssemblyVersion=${{ inputs.version }} -p:Version=${{ inputs.version }} -p:PackageVersion=${{ inputs.version }} 

  - name: Test
    shell: bash
    run: dotnet test --no-build --verbosity normal --configuration ${{ inputs.build-configuration }} --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

  - name: Code Coverage Report
    uses: irongut/CodeCoverageSummary@v1.3.0
    with:
      filename: coverage/**/coverage.cobertura.xml
      badge: true
      fail_below_min: true
      format: markdown
      hide_branch_rate: false
      hide_complexity: true
      indicators: true
      output: both
      thresholds: '60 80'

  - name: Add Coverage PR Comment
    uses: marocchino/sticky-pull-request-comment@v2
    if: github.event_name == 'pull_request'
    with:
      recreate: true
      path: code-coverage-results.md