name: Main Branch Workflow

on:
  push:
    branches: [ "main" ]

env:
  Version: '0.0.1'
  BuildConfiguration: Release

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/actions/build-and-test
      - name: Publish Nugets
        uses: ./.github/actions/publish-nugets-and-symbols