name: Main Branch Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Build & Test
        uses: ./.github/workflows/jobs/build-and-test.yml
        with:
          files: variables/common.yml variables/test.yml 
      - name: Publish Nugets
        uses: ./.github/workflows/jobs/publish-nugets-and-symbols.yml
        with:
          files: variables/common.yml variables/test.yml 