name: Main Branch Workflow

on:
  push:
    branches: [ "main" ]

env:
  Version: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          files: variables/common.yml variables/test.yml 
      - name: Publish Nugets
        uses: ./.github/actions/publish-nugets-and-symbols
        with:
          files: variables/common.yml variables/test.yml 