name: Main Branch Workflow

on:
  push:
    branches: [ "main" ]

env:
  Version: '0.0.4'
  BuildConfiguration: Release

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          build-configuration: ${{ env.BuildConfiguration }}
          version: ${{ env.Version }}
      - name: Publish Nugets
        uses: ./.github/actions/publish-nugets-and-symbols
        with:
          version: ${{ env.Version }}
          api_key: ${{ secrets.NUGET_API_KEY }}
