name: PR into Main Branch Workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  Version: '0.0.1'
  BuildConfiguration: Debug

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          build-configuration: ${{ env.BuildConfiguration }}
          version: ${{ env.Version }}