name: PR into Main Branch Workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Build & Test
        uses: ./.github/workflows/jobs/build-and-test.yml
        with:
          files: variables/common.yml variables/test.yml 