name: PR into Main Branch Workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  Version: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/workflows/jobs/build-and-test.yml
        with:
          files: variables/common.yml variables/test.yml 